### ISSUE TITLE
Retornando em tipos diferentes dependendo do status code

### ISSUE THREAD

**Issue by ricardokdz** [stone-pagamentos/stone-ecommerce-ruby#3]
Notei que os tipos de objetos retornados quando é realizado um request na api são diferentes.

Se o request der 200 retorna Hash, caso haja alguma exceção retorna String.

Sendo assim é necessário fazer uma verificação de tipo para iterar sobre as informações, caso contrário acontece erro de encode. Não seria melhor padronizar todos os retornos como Hash? Existe algum motivo especial para isso? Estou falando besteira?

Exemplo da função de post (https://github.com/stone-pagamentos/stone-ecommerce-ruby/blob/master/lib/gateway/Gateway.rb#L566):

```ruby
# funcao de post generica
def postRequest(payload, url)
  response = nil
  begin
    response = RestClient.post(url, payload, headers=@@SERVICE_HEADERS)
  rescue RestClient::ExceptionWithResponse => err
    return err.response
  end
  json_response = JSON.load response
  json_response
end
```

Exemplo do tratamento necessário:

```ruby
if order.is_a?(Hash)
  'payment ok'
  order # Hash
else
  'payment error'
  JSON.parse(order) # String
end
```

**Comment by munirwanis** [comment]
@ricardokdz obrigado por abrir a issue.
Não existe motivo especial. Você tem razão, o ideal era padronizarmos tudo para retornar Hash.
Vou levantar o quanto isto impacta os clientes pois pode quebrar uma galera com a implementação. Talvez não seja rápida a atualização pelo repositório de pacotes.

**Comment by munirwanis** [comment]
@ricardokdz foi lançada uma nova versão da SDK que corrige esses problemas.
Já está no RubyGems!
